version: '2'
services:
  cognos-categories-api:
    container_name: cognos-categories-api
    build:
      context: cognos-categories-api
      dockerfile: Dockerfile
    image: cognos-categories-api:latest
    ports:
      - 18888:8888
    networks:
      - spring-cloud-network
  product-server:
    container_name: product-server
    build:
      context: docker-product-server
      dockerfile: Dockerfile
    image: product-server:latest
    ports:
      - 19999:9999
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge
